parserInter/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', MainPageView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('personal/', PersonalView.as_view(), name='personal'),
    path('contact/', ContactView.as_view(), name='contact'),

    path('products/', ProductListView.as_view(), name='product-list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='product-update'),
    path('add-product/', AddProductView.as_view(), name='add-product'),
    path('product-in-order/<int:pk>/', ProductInOrderUpdateView.as_view(), name='product-in-order-update'),

    path('orders/', OrdersView.as_view(), name='orders'),
    path('order/delete/<int:pk>', OrderDeleteView.as_view(), name='order-delete'),
    path('delete/from/order/<int:pk>', DeleteFromOrderView.as_view(), name='delete-from-order'),
    path('repeat/order/<int:pk>', RepeatOrderView.as_view(), name='repeat-order'),

    path('cart/', CartView.as_view(), name='cart'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),

    path('send/email/', send_email, name='send-email'),
    path('send/order/', send_order, name='send-order'),

    path("login/", Login.as_view(), name="login"),
]

parserInternet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve as mediaserve
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts', include('allauth.urls')),
    path("", include('user_auth.urls')),
    path('', include('parserInter.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auth/urls.py
from django.urls import path, include

from user_auth.views import activate, register

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path('register/', register, name='register'),

    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         activate, name='activate'),
]

parserInter/models.py
from PIL import Image
from django.db import models
from datetime import date

from django.urls import reverse
from django.db.models import Sum

from user_auth.models import User
# Create your models here.


class SiteInfo(models.Model):
    email = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=100, blank=True)
    instagram_link = models.CharField(max_length=150, blank=True)
    facebook_link = models.CharField(max_length=150, blank=True)
    yelp_link = models.CharField(max_length=150, blank=True)
    company_info = models.TextField(blank=True)
    main_header = models.TextField(blank=True)
    main_header_content = models.TextField(blank=True)
    main_about = models.TextField(blank=True)
    main_content_1 = models.TextField(blank=True)
    main_content_2 = models.TextField(blank=True)
    main_products = models.TextField(blank=True)
    about_title = models.TextField(blank=True)
    about_content = models.TextField(blank=True)
    about_products_title = models.TextField(blank=True)
    about_products_content = models.TextField(blank=True)
    about_main_content = models.TextField(blank=True)
    products_content = models.TextField(blank=True)
    contact_page_content = models.TextField(blank=True)
    cart_info_cart = models.TextField(blank=True)

    def __str__(self):
        return f'Site Information'


class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    material = models.CharField(max_length=100, blank=True, null=True)
    weight = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    length = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    width = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    height = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    count = models.IntegerField()
    price = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    in_stock = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.title} / {self.count}'

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={"pk": self.id})


class Img(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    img = models.ImageField(upload_to=f'media/photos/{date.today()}')

    def __str__(self):
        return f'{self.product}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        image = Image.open(self.img.path)

        image = image.resize((1000, 1000))

        image.save(self.img.path)


class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('confirmed', 'Confirmed'),
        ('finished', 'Finished'),
    ]
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='orders')
    created_date = models.DateTimeField(auto_now=True)
    items = models.PositiveIntegerField(default=0)
    subtotal = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    tax = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    grand_total = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    confirmed = models.BooleanField(default=False)
    status = models.CharField(choices=STATUS_CHOICES, default='pending', max_length=10)


    class Meta:
        ordering = ('-id', 'status', 'created_date')

    def __str__(self):
        return f'{self.user}, {self.created_date}'

    def items_sum(self):
        return self.objects.annotate(Sum('products_in_order__count'))


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products_in_order')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='orders')
    count = models.PositiveIntegerField(default=1)
    total_price = models.PositiveIntegerField(default=0)

user_auth/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    disabled = models.BooleanField(default=False)
    username = models.CharField(max_length=100, blank=True, null=True, default='user', unique=False)
    email = models.EmailField(max_length=254, unique=True)
    first_name = models.CharField(max_length=254)
    last_name = models.CharField(max_length=254)
    phone_number = models.CharField(max_length=254, null=True, default='please enter your phone number')
    company = models.CharField(max_length=254, default='please enter the company name')
    address = models.CharField(max_length=400, default='please enter the company address')
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(null=True, auto_now=True)
    joined_date = models.DateTimeField(default=timezone.now())
    discount = models.IntegerField(null=True, default=0)
    total_amount = models.IntegerField(null=True)
    from_google = models.BooleanField(default=True)

    class Meta:
        ordering = ('disabled',)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

parserInter/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from parserInter.models import Product, Order, ProductInOrder, SiteInfo


class EmailForm(forms.Form):
    first_name = forms.CharField(max_length=100, min_length=2)
    last_name = forms.CharField(max_length=100, min_length=2)
    email = forms.EmailField()
    message = forms.CharField(max_length=3000)


class EmailOrderForm(forms.Form):
    first_name = forms.CharField(max_length=100, min_length=2)
    last_name = forms.CharField(max_length=100, min_length=2)
    phone_number = forms.CharField(max_length=20, min_length=2)
    email = forms.EmailField()
    message = forms.CharField(max_length=3000)
    grand_total = forms.CharField(max_length=10)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'user',
            'items',
            'subtotal',
            'tax',
            'discount',
            'grand_total',
        )


class SiteAdminForm(forms.ModelForm):
    about_main_content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = SiteInfo
        fields = '__all__'

templates/parserInter/about.html
{% extends 'base.html' %}
{% load static %}
{% load contact_info_tags %}
{% get_contact_info as info %}
{% block header_content %}
            <div class="header-content header-pages">
                <h1 class="namepage">About us</h1>
            </div>
{% endblock %}

{% block content %}

    <!-- SECTION: About Us-->
    <section class="info">
        <div class="container content-about">
            <div class="row mb-5">
                <div class="title-page-about">
                    {{ info.about_title }}
                </div>
                <div class="text-page-about">
                    {{ info.about_content }}
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-6 right-content mobile-col-none">
                    <p>{{ info.about_main_content|safe }}</p>
                </div>

                <div class="col-md-6 col-6 mobile-col-6">
                    <div class="image-page-about"></div>
                </div>
            </div>
        </div>
        <div class="greenback" style="height: 386px;"></div>
    </section>

    <div class="container">
        <section class="about-content-2">
            <div class="about-text">
                <div class="about-content-text">{{ info.about_products_title }}</div>
                <div class="about-content-text2">
                    {{ info.about_products_content }}
                </div>
            </div>
    
            <div class="about-images">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <a href="{% url 'product-list' %}" class="about-img-content">
                            <div class="about-content-image2"><img src="{% static '/image/page-about.jpg' %}" alt="" style="max-width: 100%; max-height: 100%"></div>
                            <div class="about-content-imgtext">our products</div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </div>


{% endblock %}

templates/parserInter/cart.html
{% extends 'base.html' %}
{% load contact_info_tags %}
{% get_contact_info as info %}
{% block header_content %}
<div class="header-content header-pages">
<h1 class="namepage">Shopping cart</h1>
</div>
{% endblock %}
{% block content %}
    <!-- SECTION: Contact -->
    <section class="info">
        <div class="container content-cart">
            {% for object in object_list %}
            <div class="row">
                    {% for products in object.products_in_order.all %}
                        <div class="col-md-3">
                            <div class="product">
                                <div class="product-image">
                                    {% for image in products.product.images.all %}
                                        {% if forloop.first %}
                                            <img src="{{ image.img.url }}" alt="" style="width: 100%; max-height: 100%;">
                                        {% endif %}
                                    {% endfor %}
                                    <a href="{% url 'delete-from-order' products.id %}" class="removegoods"><i class="las la-times"></i></a></div>
                                <div class="product-body">
                                    <form class="formchange{{ products.id }}" action="{% url 'product-in-order-update' products.id %}" method="POST">
                                        {% csrf_token %}
                                        <div class="product-name"><a href="{% url 'product-detail' products.product.id %}">{{ products.product.title }}</a></div>
                                        <div class="producАt-desc">{{ products.product.description|truncatechars:30 }}</div>
                                        <div class="select-count-cart">
                                            <div class="number" data-step="1" data-min="1" data-max="100">
                                                <input type="hidden" class="obj_id" value="{{ products.id }}" name="obj_id">
                                                <input type="hidden" class="priceforone" value="{{ products.product.price }}">
                                                <input class="number-text" type="text" name="count" value="{{ products.count }}">
                                                <a href="#" class="number-minus">−</a>
                                                <a href="#" class="number-plus">+</a>
                                            </div>
                                        </div>
                                        <div class="goods-cost">{{ products.total_price }} $ </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            </div>
            <div class="row">
                <div class="goods">
                    <div class="mb-5">
                        <div class="totalinfo">
                            <div class="totalcost items_total"><b>Items: {{ object.items }}</b></div>
                            <div class="totalcost"><b>Subtotal:</b>{{ object.subtotal }}</div>
                            <div class="totalcost"><b>Estimated tax to be collected:</b>{{ object.tax }}</div>
                            <div class="totalcost"><b>Discount:</b>{{ object.discount }}</div>
                            <div class="totalcost price_total"><b>Grand Total: {{ object.grand_total }} $</b></div>
                        </div>
                    </div>
                    <div class="mb-3 rightcart">
                        <form action="{% url 'send-order' %}" method="POST", id="order_form">
                        {% csrf_token %}
                        <input type="hidden" name="order" value="{{ object.id }}">

                        <div class="mb-3">
                            <input type="hidden" name="first_name" value="{{ user.first_name }}">
                        </div>
                        <div class="mb-3">
                            <input type="hidden" name="last_name" value="{{ user.last_name }}" >
                        </div>
                        <div class="mb-3">
                            <input type="hidden" name="email" value="{{ user.email }}" >
                        </div>
                        <div class="mb-3">
                            <input type="hidden" name="phone_number" value="{{ user.phone_number }}" >
                        </div>
                        <div class="mb-3">
                            <input type="hidden" name="grand_total" value="{{ object.grand_total }}" >
                        </div>
                        <div class="mb-3">
                            <input type="hidden" name="message" value='{% for product in object.products_in_order.all %}
                            {{ product.product.title }}: {{ product.count }} / {{ product.total_price }}$,
                            {% endfor %}'>
                        </div>
                        <div class="mb-3">
                            <button id="btn" type="submit"  class="payment">Create an order</button>
                        </div>
                    </form>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
<div id="popup" style="display: none;">
        <button id="cancel">×</button>

  <p>{{ info.cart_info_cart }}</p>
  <div class="button-container">
    <button id="ok">OK</button>
  </div>
</div>
    </section>



<script>
const btn = document.getElementById("btn");
const popup = document.getElementById("popup");
const ok = document.getElementById("ok");
const cancel = document.getElementById("cancel");
const orderForm = document.getElementById("order_form");

btn.addEventListener("click", function(event) {
  event.preventDefault();
  popup.style.display = "block";
});

ok.addEventListener("click", function() {
  popup.style.display = "none";
  orderForm.submit();
});

cancel.addEventListener("click", function() {
  popup.style.display = "none";
});
</script>
<style>
#popup {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: white;
  padding: 5px 20px 10px;
  border: 1px solid black;
  box-shadow: 2px 2px 10px rgba(0,0,0,0.3);
  border-radius: 5px;
  width: 500px;
  height: auto; /* Height can increase as needed */
  display: flex;
  flex-direction: column;
}

.popup-buttons {
  display: flex;
  justify-content: flex-end;
  margin-top: auto; /* Pushes the buttons towards the bottom */
  padding-top: 20px;
  padding-bottom: 20px;

}

button#close {
  position: absolute;
  right: -3px;
  top: -5px;
  font-size: 20px;
  background-color: transparent;
  border: none;
  color: black;
}

button.popup-button {
  border: 2px solid #008041;
  background-color: #008041;
  color: white;
  padding: 10px 20px;
  border-radius: 5px;
  margin-left: 20px;
  cursor: pointer;
}

/* Make the popup responsive */
@media only screen and (max-width: 600px) {
  #popup {
    width: 80%;
    height: auto;
  }
}
#ok{
    border: 2px solid #008041;
    border-radius: 5px;
    padding: 5px;
    background-color: #008041;
    color: white;
    font-size: 16px;
    margin-left: 2px;
    cursor: pointer;
    width: 80px;
}
#cancel{
    text-align: center;
    border: none;
    background-color: transparent;
    margin-left: 95%;
    font-size: 25px;
}
</style>

    <script>
const minusButtons = document.querySelectorAll('.number-minus');
const plusButtons = document.querySelectorAll('.number-plus');
const countInputs = document.querySelectorAll('.number-text');
const priceForOneInputs = document.querySelectorAll('.priceforone');
const totalCostDivs = document.querySelectorAll('.goods-cost');
const totalItems = document.querySelector('.items_total b:first-of-type');
const grandTotal = document.querySelector('.price_total b:last-of-type');
const forms = document.querySelectorAll("form");

let items = 0;
let total = 0;

for (let i = 0; i < minusButtons.length; i++) {
  minusButtons[i].addEventListener('click', (e) => {
    e.preventDefault();
    let count = parseInt(countInputs[i].value);
    if (count > 1) {
      count -= 1;
      countInputs[i].value = count;
      totalCostDivs[i].innerHTML = count * parseInt(priceForOneInputs[i].value) + ' $';
      updateTotal(count, i, e.target.closest("form"));
    }
  });

  plusButtons[i].addEventListener('click', (e) => {
    e.preventDefault();
    let count = parseInt(countInputs[i].value);
    count += 1;
    countInputs[i].value = count;
    totalCostDivs[i].innerHTML = count * parseInt(priceForOneInputs[i].value) + ' $';
    updateTotal(count, i, e.target.closest("form"));
  });
}

function updateTotal(count, i, form) {
  let objIdInput = form.querySelector("input[name='obj_id']");
  let csrfToken = form.querySelector("input[name='csrfmiddlewaretoken']").value;
  let xhr = new XMLHttpRequest();
  xhr.open("POST", form.action, true);
  xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
  xhr.send("csrfmiddlewaretoken=" + csrfToken + "&obj_id=" + objIdInput.value + "&count=" + count );

  xhr.onreadystatechange = function() {
    if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {
      items = 0;
      total = 0;
      for (let i = 0; i < countInputs.length; i++) {
        items += parseInt(countInputs[i].value);
        total += parseInt(countInputs[i].value) * parseInt(priceForOneInputs[i].value);
      }
      totalItems.innerHTML = 'Items: ' + items;
      grandTotal.innerHTML = 'Grand Total :' + total + ' $';
    }
  };
}

</script>

<style>
.changebtn{
background-color: #FAF4F2;
color: #3E1E02;
padding: -3px 5px;
border-radius: 5px;
text-align: center;
cursor: pointer;
border: 1px #DDDDDD solid;
}
</style>

{% endblock %}

templates/parserInter/contact.html
{% extends 'base.html' %}
{% load contact_info_tags %}
{% get_contact_info as info %}
{% block header_content %}
            <div class="header-content header-pages">
                <h1 class="namepage">Contact us</h1>
            </div>
{% endblock %}


{% block content %}

    <!-- SECTION: Contact -->
    <section class="info">
        <div class="container content-contact">
            <div class="row">
                <div class="col-md-6">
                    <div class="contact-content-title">
                        Contacts
                    </div>

                    <div class="contact-content-desc">
                        {{ info.contact_page_content }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="contact-list">
                        <div class="contact-element">
                            <div class="icon-green-mail"></div>
                            <div class="text-contact">{{ info.email }}</div>
                        </div>

                        <div class="contact-element">
                            <div class="icon-green-telephone"></div>
                            <div class="text-contact">{{ info.phone }}</div>
                        </div>

                        <div class="contact-element">
                            <div class="icon-green-facebook"></div>
                            <a href="{{ info.facebook_link }}"><div class="text-contact">Connect in Facebook</div></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


 {% endblock %}

templates/parserInter/delete_confirm.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <h1>Are you sure you want to delete #{{ object.id }}?</h1>
        <div class="flexbox" style="display: flex; flex-wrap: wrap">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete" class="modalbtn" style="margin:5px">
    </form>
        <br>
        <a href="{% url 'orders' %}"><button class="modalbtn" style="margin: 4px;">Cancel</button></a>
        <br>
    </div>
    <br>
    </div>
{% endblock %}

templates/parserInter/index.html
{% extends 'base.html' %}
{% load contact_info_tags %}
{% get_contact_info as info %}

{% block header_content %}
            <div class="header-content">
                <div class="header-content-text">
                    <div class="header-title">
                        {{ info.main_header }}
                    </div>
                    <div class="header-desc">
                        {{ info.main_header_content }}
                    </div>
                </div>

            </div>
{% endblock %}


{% block content %}

    <!-- SECTION: About Us-->
    <section class="aboutus">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="image-aboutus"></div>
                </div>

                <div class="col-md-8">
                    <div class="text-aboutus">
                        <div class="text-content">
                            <span class="headline">About us</span>
                            {{ info.main_about }}
                        </div>

                        <a href="{% url 'about' %}" class="readmore">read more</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="info">
        <div class="container content-index">
            <div class="row">
                <div class="col-md-6 col-6 right-content">
                    <div class="text-info-content">
                        <div class="text-info-1">
                            {{ info.main_content_1 }}
                        </div>

                        <div class="text-info-2">
                            {{ info.main_content_2 }}
                        </div>
                    </div>

                    <div class="image-info"></div>
                </div>

                <div class="col-md-6 col-6">
                    <div class="image-water"></div>
                </div>
            </div>
        </div>
        <div class="greenback"></div>
    </section>

    <!-- PRODUCTS -->
    <div class="container">
        <div class="products-content">
            <div class="content-header">
                <h2 class="content-title">Products</h2>
                <h6 class="content-desc">
                    {{ info.main_products }}
                </h6>
            </div>

            <div class="content">
                <div class="owl-carousel owl-theme products-carousel">
                    {% for object in object_list %}
                    <div class="item">
                        <div class="product">
                            {% for image in object.images.all %}
                                {% if forloop.first %}
                                    <div class="product-image"><a href="{% url 'product-detail' object.id %}"><img src="{{ image.img.url }}" alt="" style="width: 100%;"></a></div>
                                {% endif %}
                            {% endfor %}

                            <div class="product-body">
                                <div class="product-name">{{ object.title }}</div>
                                <div class="product-desc">{{ object.description|truncatechars:100 }}</div>
                            </div>
                        </div>

{#                        <div class="product">#}
{#                            <div class="product-image"></div>#}
{#                            <div class="product-body">#}
{#                                <div class="product-name">Products</div>#}
{#                                <div class="product-desc">Ask CDCR San Quintin State Prison 2008. </div>#}
{#                            </div>#}
{#                        </div>#}
                    </div>

                    {% endfor %}

                </div>

                <script>
                    $('.products-carousel').owlCarousel({
                        loop:true,
                        margin:10,
                        nav:true,
                        responsive:{
                            0:{
                                items:2
                            },
                            600:{
                                items:2
                            },
                            1000:{
                                items:4
                            }
                        }
                    })
                </script>
            </div>
        </div>
    </div>

{% endblock %}

templates/parserInter/personal.html
{% extends 'base.html' %}
{% block header_content %}
            <div class="header-content header-pages">
                <h1 class="namepage">Personal</h1>
            </div>
{% endblock %}

{% block content %}

    <!-- SECTION: Contact -->
    <section class="info">
        <div class="container content-cart">
            <div class="mb-3">
                <input type="password" class="form-control form-control-form" placeholder="Password">
            </div>

            <div class="mb-3">
                <input type="password" class="form-control form-control-form" placeholder="New password">
            </div>

            <div class="mb-3">
                <input type="password" class="form-control form-control-form" placeholder="Confirm New Password">
            </div>

            <div class="mb-5">
                <a href="/" class="payment">Save</a>
            </div>
        </div>
    </section>

{% endblock %}

templates/parserInter/profile_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">

    <div class="profile-container">
        <h1>Edit Profile</h1>
        <form method="POST" enctype="multipart/form-data" action="{% url 'profile-update' object.id %}">
            {% csrf_token %}
                <div class="profileupdate">
                <p>
    <label for="id_first_name">First name:</label><br>
    <input type="text" name="first_name" value="{{ object.first_name }}" maxlength="254" required="" id="id_first_name">
  </p>
  <p>
    <label for="id_last_name">Last name:</label><br>
    <input type="text" name="last_name" value="{{ object.last_name }}" maxlength="254" required="" id="id_last_name">
  </p>
  <p>
    <label for="id_email">Email:</label><br>
    <input type="email" name="email" value="{{ object.email }}" maxlength="254" required="" id="id_email">
  </p>
  <p>
    <label for="id_phone_number">Phone number:</label><br>
    <input type="text" name="phone_number" data-value="{{ object.phone_number }}" maxlength="254" required="" id="id_phone_number">

  </p>

  <p>
    <label for="id_company">Company:</label><br>
    <input type="text" name="company" data-value="{{ object.company }}" maxlength="254" required="" id="id_company">
  </p>

  <p>
    <label for="id_address">Address:</label><br>
    <input type="text" name="address" data-value="{{ object.address }}" maxlength="400" required="" id="id_address">
  </p>
                </div>
            <input type="submit" value="Save changes"class="modalbtn"  style="margin-bottom: 20px">
        </form>
    </div>
    </div>

    <style>
form label{margin-left: 10px}
form input{border:1px solid rgba(66,63,63,0.5);border-radius:0;padding:5px 20px; width: 500px}

    </style>
{% endblock %}